name: Bonjour
on:
  - push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "bonjour!"
